# Generated by Django 4.0 on 2022-01-03 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_first_name_user_is_admin_user_is_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(max_length=600, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships_created', to='accounts.user', verbose_name='admin')),
                ('evaluators', models.ManyToManyField(related_name='scholarships_assigned', to=settings.AUTH_USER_MODEL, verbose_name='agents')),
            ],
            options={
                'verbose_name': 'scholarship',
                'verbose_name_plural': 'scholarships',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(max_length=300, verbose_name='description')),
                ('attachment', models.FileField(blank=True, upload_to='attachments', verbose_name='file')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='scholarships.scholarship', verbose_name='scholarship')),
            ],
            options={
                'verbose_name': 'required document',
                'verbose_name_plural': 'required documents',
            },
        ),
    ]
