# Generated by Django 4.0 on 2022-01-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_requireddocument_description_and_more'),
        ('rooms', '0002_alter_document_reviewed_by_alter_message_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requirement',
            field=models.ForeignKey(default='36a1bb8c-19b8-45c5-985e-65df88121ce5', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarships.requireddocument', verbose_name='requirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rooms.room', verbose_name='campaign'),
        ),
    ]
