# Generated by Django 4.0 on 2022-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_document_requirement_alter_document_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='content'),
        ),
    ]
